version: '3.7'

services:
  postgresql:
    image: postgres:12-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=zxcvbn1234